FROM node:20-alpine AS builder
WORKDIR /app
COPY cookinoshop2.0/package*.json ./
RUN npm install
COPY cookinoshop2.0/ .
RUN npm run build


FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
