name: cookino-shop

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/02_schema.sql:ro
      - ./postgres/seed.sql:/docker-entrypoint-initdb.d/03_seed.sql:ro

    networks:
      - cookino_network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  mongodb:
    image: mongo:8.0
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    volumes:
      - mongo_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/01_init-mongo.js:ro
      - ./mongodb/seed-products.js:/docker-entrypoint-initdb.d/02_seed-products.js:ro

    networks:
      - cookino_network

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping').ok"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s


networks:
  cookino_network:
    name: cookino_network


volumes:
  postgres_data:
    name: cookino_postgres_data

  mongo_data:
    name: cookino_mongo_data